### ISSUE TITLE
Ecto support

### ISSUE THREAD

**Issue by onelesd** [MyMedsAndMe/marco_polo#43] opened 2016-08-10 20:41 UTC
@whatyouhide You referenced work on Ecto support for this driver in #19. Curious if that is still in the works or not? It is an effort I'd be happy to contribute to.

Fwiw, I'm currently using ex_orient (mainly for it's poolboy integration out of the box), but it doesn't offer any Ecto support.

**Comment by whatyouhide** [comment] 2016-08-10 20:55
Hey @onelesd, thanks for the interest :) Sadly no, Ecto support is not in the plans for the future anymore. We discussed this several times, and we see integration just as not worth: OrientDB uses a "proprietary" SQL dialect that would be harder to support in Ecto (especially the area around the graph side of OrientDB); this alone makes integration with Ecto hard to realize in practice. Ecto would also bring pooling, schema, and migrations: the first can be easily achieved with something like poolboy (as you mentioned), the other two are the things you would have to implement yourself if you need them in your application.

While I don't deem an adapter for Ecto worth it, you're obviously free to give it a shot yourself, I am available for advice and help if needed (on my free time, so not too much time 😄). Let me know if I can do anything else! Gonna close this issue now because it's not a bug or feature request per se, but feel free to keep the discussion going here.

**Closed by whatyouhide** 2016-08-10 20:55 UTC

**Comment by onelesd** [comment] 2016-08-10 21:01
I agree, Ecto integration is not a small undertaking. The schema is of less interest to me than the migrations, as it can be difficult to collaborate on projects without them.

My first thought is that a couple of mix tasks could easily do the job, but I'm curious how you've handled migrations on your projects?

**Comment by whatyouhide** [comment] 2016-08-10 21:03
@onelesd I personally never worked on a project that uses OrientDB, I only worked on this driver. I know other people in @MyMedsAndMe/voyagers that participated in MarcoPolo use OrientDB in their stack, so maybe they are able to give more advice in this area :)

Btw yeah, likely you could achieve migrations with a couple of not-too-complex Mix tasks.
